Repository surajm-333/Ace-The-FrontEnd, pull requests merged in 2022-05, with the labels that each got.

#520 Shoppingcart
  Shopping Cart/index.html
  Shopping Cart/style.css
Labels: GSSoC22

#654 clipboard-product-landing-page
  clipboard-landing-page/.gitignore
  clipboard-landing-page/README.md
  clipboard-landing-page/design/active-states.jpg
  clipboard-landing-page/design/desktop-design.jpg
  clipboard-landing-page/design/desktop-preview.jpg
  clipboard-landing-page/design/mobile-design.jpg
  clipboard-landing-page/images/bg-header-desktop.png
  clipboard-landing-page/images/bg-header-mobile.png
  clipboard-landing-page/images/favicon-32x32.png
  clipboard-landing-page/images/icon-blacklist.svg
  clipboard-landing-page/images/icon-facebook.svg
  clipboard-landing-page/images/icon-instagram.svg
  clipboard-landing-page/images/icon-preview.svg
  clipboard-landing-page/images/icon-text.svg
  clipboard-landing-page/images/icon-twitter.svg
  clipboard-landing-page/images/image-computer.png
  clipboard-landing-page/images/image-devices.png
  clipboard-landing-page/images/logo-google.png
  clipboard-landing-page/images/logo-hp.png
  clipboard-landing-page/images/logo-ibm.png
  clipboard-landing-page/images/logo-microsoft.png
  clipboard-landing-page/images/logo-vector-graphics.png
  clipboard-landing-page/images/logo.svg
  clipboard-landing-page/index.html
  clipboard-landing-page/style.css
Labels: plaigarised

#721 Added Age Calculator
  Age_Calculator/images.png
  Age_Calculator/index.html
  Age_Calculator/index.js
  Age_Calculator/style.css
Labels: GSSoC22, Level1

#722 Added Animated Heartbeat
  Animated_Heartbeat/index.html
  Animated_Heartbeat/logo.png
  Animated_Heartbeat/style.css
Labels: GSSoC22, Level1

#744 Drag and Drop
  Drag-n-drop/README.md
  Drag-n-drop/app.js
  Drag-n-drop/index.html
  Drag-n-drop/style.css
Labels: GSSoC22, Level2

#740 3D rotating cube
  3D-rotating cube/cube.html
  3D-rotating cube/style.css
Labels: GSSoC22, Level1

#708 Portfolio
  Portfolio Website/asset/cityscapes.png
  Portfolio Website/asset/cloud.png
  Portfolio Website/asset/code.png
  Portfolio Website/asset/joystick.png
  Portfolio Website/asset/logo.png
  Portfolio Website/index.html
  Portfolio Website/readme.md
  Portfolio Website/style.css
Labels: GSSoC22, Level2
